[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "neuromata"
readme = "README.md"
version = "0.0.1"
requires-python = ">=3.10"

[tool.hatch.build.targets.wheel]
packages = ["src/neuromata"]

[tool.isort]
known_third_party = ["wandb"]
